pipeline {
    agent any
    environment{
        TARGET_HOST = "ubuntu@52.79.110.20"
        IMAGE_NAME = "front/develop"
        CONTAINER_NAME ="front_develop"
        VERSION = "1.0"
        PROJECT_PATH = "/home/ubuntu/front-develop"
    }
    stages {
        stage('Clone') {
            steps {
                git branch: 'fe_develop', credentialsId: 'cookscape' ,url: 'https://lab.ssafy.com/s08-metaverse-game-sub2/S08P22B109.git'
            }
        }
        stage('Build') {
            steps {
                dir("./Frontend/cookscape"){
                   sshagent (credentials: ['cookscape_ssh']){
                        sh 'scp -o StrictHostKeyChecking=no -r ./* ${TARGET_HOST}:${PROJECT_PATH}'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                 echo  '테스트 단계와 관련된 몇 가지 단계를 수행합니다.'
            }
        }
        stage('Stop process'){
            steps{
                sshagent (credentials: ['cookscape_ssh']){
                    script{
                        try{
                            sh'''
                             ssh -o StrictHostKeyChecking=no ${TARGET_HOST} "docker rm -f ${CONTAINER_NAME}"
                             ssh -o StrictHostKeyChecking=no ${TARGET_HOST} "docker rmi ${IMAGE_NAME}:${VERSION}"
                             '''
                        } catch (e){
                            echo 'Remove Container Failed : ${CONTAINER_NAME}'
                        }
                    }

                }
            }
        }
        stage('Deploy'){
            steps{
                sshagent (credentials: ['cookscape_ssh']){
                   sh'''
                   ssh -o StrictHostKeyChecking=no ${TARGET_HOST} "docker build --tag ${IMAGE_NAME}:${VERSION} ${PROJECT_PATH}"
                   ssh -o StrictHostKeyChecking=no ${TARGET_HOST} "docker run --name ${CONTAINER_NAME} -p 3000:3000 -d ${IMAGE_NAME}:${VERSION}"
                   '''
                }
            }
        }
    }
}
